project:
  type: book

book:
  title: "DL Python"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/py-dl
  site-url: https://py-dl-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Math
      chapters: 
        - "contents/math/partial-derivative.qmd"
    - part: History
      chapters: 
        - "contents/history/cnn-evolution-01.qmd"
        - text: "Classification Model"
          href: "contents/history/classification-model-evolution.qmd"
        - text: "Segmentation Model"
          href: "contents/history/segmentation-model-evolution.qmd"
    - part: Intro
      chapters: 
        - "contents/overview/pre_trained_networks.ipynb"
    - part: Concept
      chapters: 
        - text: Gradient
          href: "contents/concept/gradient-func.qmd"
        - text: Parameter Estimation
          href: "contents/concept/1_parameter_estimation.ipynb"
    - part: Tensor
      chapters: 
        - "contents/tensor/tensor-00-anatomy.qmd"
        - "contents/tensor/tensor-00-tutorial-official.ipynb"
        - "contents/tensor/tensor-01-basic.ipynb"
        - "contents/tensor/tensor-02-viz.ipynb"
        - "contents/tensor/tensor-03-named-tensor.ipynb"
        - "contents/tensor/tensor-squeeze.qmd"
        - text: "Contiguous Tensor"
          href: "contents/tensor/tensor-contiguous.qmd"
        - text: "Save & Load Tensor"
          href: "contents/tensor/tensor-save-load.qmd"
        - text: "Stack"
          href: "contents/tensor/tensor-stack.qmd"
        - text: "View"
          href: "contents/tensor/tensor-view.qmd"
    - part: Preprocessing
      chapters: 
        - text: 2D Image Data
          href: "contents/pytorch/working-w-img/1_image_dog.ipynb"
        - text: CT Data
          href: "contents/pytorch/working-w-ct/2_volumetric_ct.ipynb"
    - part: Feature Processing
      chapters: 
        - "contents/proc-feat/conv-2d3d.qmd"
    - part: Logistic Regression
      chapters: 
        - "contents/logreg/pytorch-logreg-concept.qmd"
        - "contents/logreg/pytorch-logreg.ipynb"
    - part: AlexNet Layers
      chapters: 
        - "contents/alexnet-layers/01-conv2d.qmd"
        - "contents/alexnet-layers/02-MaxPool2d.qmd"
        - "contents/alexnet-layers/03-features.qmd"
        - "contents/alexnet-layers/04-avgpool.qmd"
        - "contents/alexnet-layers/05-classifier.qmd"
        - "contents/alexnet-layers/06-alexnet-params.qmd"
    - part: ResNet Layers
      chapters: 
        - "contents/resnet/resnet-01-explore.ipynb"
        - "contents/resnet/resnet-02-overview.qmd"
        - "contents/resnet/resnet-03-BatchNorm2d.qmd"
        - "contents/resnet/resnet-04-skip-connection.qmd"
    - part: Keras
      chapters: 
        - "contents/keras/keras-mini-resnet-mnist.qmd"
    - part: PyTorch
      chapters: 
        - "contents/pytorch/torch_simple_model.ipynb"
        - "contents/pytorch/torch_dataloader.ipynb"
        - "contents/pytorch/torch_training_loop.ipynb"
    - references.qmd


format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: 
      - darkly
    toc-depth: 4


freeze: auto